# site settings

title: Patty Yu-Lan Liu
description: A software engineer based on Vancouver, BC, Canada
taglong: Software Engineer based on Vancouver, Canada
tagshort: Patty Liu
url: https://ikulan.github.io
baseurl: "/personal_website_v1"
permalink: pretty
repo: https://github.com/ikulan/personal_website_v1

# author settings

author:
  name: ikulan
  email: ikulan@gmail.com
photo: /assets/photo.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
